version: '3.8'

services:
  app:
    build: .
    image: dmweggemans/tasktracker-api:latest
    container_name: tasktracker-app

    ports:
      - "8080:8080"

    volumes:
      - tasktracker-db:/tasktracker-db

    restart: unless-stopped

volumes:
  tasktracker-db: